export default {
  fontSizeSm: '12px',
  fontSizeMd: '14px',
  fontSizeLg: '16px',
  buttonPaddingSm: '4px 10px',
  buttonPaddingMd: '6px 15px',
  buttonPaddingLg: '8px 18px',
  inputPaddingSm: '4px 2px',
  inputPaddingMd: '6px 4px',
  inputPaddingLg: '8px 6px',
  inputRadioGap: '20px',
  inputRadioTextGap: '5px',
  selectDropdownOffsetTopSm: '26px',
  selectDropdownOffsetTopMd: '30px',
  selectDropdownOffsetTopLg: '34px',
  selectOptionMargin: '2px 0',
  selectOptionPadding: '4px 10px',
  selectOptionBgColor: '#fff',
  selectOptionActiveBgColor: '#6fb4fc',
  formFieldBorderColorDisabled: '#ddd',
  formFieldBgColorDisabled: '#e8e8e8',
  formFieldFontColorDisabled: '#bdbdbd',
  formFieldBorderRadius: '2px',
};