export default {
  fontSizeSm: '12px',
  fontSizeMd: '14px',
  fontSizeLg: '16px',
  buttonPaddingSm: '4px 10px',
  buttonPaddingMd: '6px 15px',
  buttonPaddingLg: '8px 18px',
  inputPaddingSm: '4px 2px',
  inputPaddingMd: '6px 4px',
  inputPaddingLg: '8px 6px',
  inputRadioGap: '20px',
  inputRadioTextGap: '5px',
  formFieldBorderColorDisabled: '#ddd',
  formFieldBgColorDisabled: '#e8e8e8',
  formFieldFontColorDisabled: '#bdbdbd',
};